version: "3.8"

services:
  # API Service
  api:
    build:
      context: ./Backend/SideBySideAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./Backend/SideBySideAPI:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=SideBySide
      - Redis__ConnectionString=redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - side-by-side-network

  # MongoDB Service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - side-by-side-network

  # Redis for Caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - side-by-side-network

  # OCR Service (Tesseract)
  tesseract:
    build:
      context: ./Tesseract
      dockerfile: Dockerfile
    volumes:
      - tesseract_data:/usr/share/tesseract-ocr/4.00/tessdata
    networks:
      - side-by-side-network

volumes:
  mongodb_data:
  redis_data:
  tesseract_data:

networks:
  side-by-side-network:
    driver: bridge
