name: Validate Docker Compose

on:
  push:
    branches: [main]
    paths:
      - "docker-compose*.yml"
  pull_request:
    branches: [main]
    paths:
      - "docker-compose*.yml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Validate docker-compose.yml
        run: docker-compose config

      - name: Test containers startup
        run: |
          docker-compose up -d
          sleep 30
          docker-compose ps
          docker-compose logs
          docker-compose down
